### ISSUE TITLE
do you have 1txs drc-20 inscribe script?

### ISSUE THREAD

**Issue by fhhg9658** [Skr1pt/DogeInscriber#1]

**Comment by Skr1pt** [comment]
check README, you can change data for deploy, mint, transfer functions or what you want

**Comment by fhhg9658** [comment]
Hello, take a look at this.

https://chain.so/tx/DOGE/e062ab23377aa9ca46a783f85012a6faf802a37bc5f5f0ce1d89a61cb6e6cc4c

Can your script be minted in this way?

**Comment by Skr1pt** [comment]
> Hello, take a look at this.
> 
> https://chain.so/tx/DOGE/e062ab23377aa9ca46a783f85012a6faf802a37bc5f5f0ce1d89a61cb6e6cc4c
> 
> Can your script be minted in this way?

currently not, but I can add this feature

**Comment by fhhg9658** [comment]
Hello, can you add this feature to MINT? I only know how to use. js, I am an outsider. I am willing to pay a fee to obtain this feature. I don't know how much it will cost?
Have you ever used Ordifind's mint feature? What I'm talking about is the mind mode like it.

**Comment by Skr1pt** [comment]
> Hello, can you add this feature to MINT? I only know how to use. js, I am an outsider. I am willing to pay a fee to obtain this feature. I don't know how much it will cost? Have you ever used Ordifind's mint feature? What I'm talking about is the mind mode like it.

give me your telegram contact or msg to my (check readme)

**Comment by fhhg9658** [comment]
do you have Twitter?

Hello, I mean I want to add a batchmint function similar to dunes script to this drc-20 script.

https://github.com/martinseeger2002/doginals/blob/main/doginals.js

I use this script but it doesn't have batchmint functionality like dune, can you add batchmint functionality to this script?

**Comment by fhhg9658** [comment]
Please turn on the teleregram strictions so that I can send you messages
